### ISSUE TITLE
Delete sidebar

### ISSUE THREAD

**Issue by ikender** [blazersix/simple-page-sidebars#4]
Created a sidebar that was unnecessary and would like to remove it... is there a way to do this without database editing?

**Comment by bradyvercher** [comment]
You just need to unassign the sidebar from any page that's using it and it will be removed.

**Comment by ikender** [comment]
Thanks... I had the page sitting in the trash, when I permanently deleted it the sidebar removed itself...  My apologies for not doing that first

**Comment by bradyvercher** [comment]
No problem! Glad to hear you got it worked out.
